export {default as Main} from './Main/Main';
export {default as App} from './App/App';
export {default as Orientation} from './Orientation/Orientation';
export {default as Questionaire} from './Questionaire/Questionaire';
export {default as Results} from './Results/Results';
export {default as Question} from './Question/Question';
export {default as Death} from './Death/Death';
export {default as DeathResults} from './DeathResults/DeathResults';
export {default as ToastList} from './ToastList/ToastList';